# Trabalho Prático 1

## Carregamento dos dados

In [1]:
import ir_datasets
import pandas as pd

dataset = ir_datasets.load("cranfield")

docs = pd.DataFrame(
    dataset.docs_iter(),
    columns=["doc_id", "title", "text", "author", "bib"]
)

docs.head()

[INFO] [starting] http://ir.dcs.gla.ac.uk/resources/test_collections/cran/cran.tar.gz
[INFO] [finished] http://ir.dcs.gla.ac.uk/resources/test_collections/cran/cran.tar.gz: [00:01] [50

,doc_id,title,text,author,bib
0,1,experimental investigation of the aerodynamics...,experimental investigation of the aerodynamics...,"brenckman,m.","j. ae. scs. 25, 1958, 324."
1,2,simple shear flow past a flat plate in an inco...,simple shear flow past a flat plate in an inco...,ting-yili,"department of aeronautical engineering, rensse..."
2,3,the boundary layer in simple shear flow past a...,the boundary layer in simple shear flow past a...,m. b. glauert,"department of mathematics, university of manch..."
3,4,approximate solutions of the incompressible la...,approximate solutions of the incompressible la...,"yen,k.t.","j. ae. scs. 22, 1955, 728."
4,5,one-dimensional transient heat conduction into...,one-dimensional transient heat conduction into...,"wasserman,b.","j. ae. scs. 24, 1957, 924."

In [2]:
queries = pd.DataFrame(
    dataset.queries_iter(),
    columns=["query_id", "text"]
)

queries.head()

  query_id                                               text
0        1  what similarity laws must be obeyed when const...
1        2  what are the structural and aeroelastic proble...
2        3  what problems of heat conduction in composite ...
3        4  can a criterion be developed to show empirical...
4        5  what chemical kinetic system is applicable to ...

In [3]:
qrels = pd.DataFrame(
    dataset.qrels_iter(),
    columns=["query_id", "doc_id", "relevance", "iteration"]
)

qrels.head()

  query_id doc_id  relevance iteration
0        1    184          2         0
1        1     29          2         0
2        1     31          2         0
3        1     12          3         0
4        1     51          3         0

In [4]:
docs.to_csv("data/cranfield_docs.csv", index=False)
queries.to_csv("data/cranfield_queries.csv", index=False)
qrels.to_csv("data/cranfield_qrels.csv", index=False)

## Continuação